### ISSUE TITLE
Refresh button animation

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#136]
Bells and whistles

Refresh button should have the same cycle animation as the on off. For coherence sake eheh

**Comment by dllud** [comment]
I can't see why and how. How would we determine the state (i.e. the painted area) of the refresh button?
Also I see no reason to spoil the action bar with animations and with a button of a different colour.

**Comment by algazarra** [comment]
If price hasn't changed the user may think it isn't updating. The button stays as is and only animates like he on off when updating. The idea is to keep the bar as clean as possible. But make the design a little bit more responsive.

**Comment by dllud** [comment]
But there is feedback. After hitting refresh, all alarms update and their ON/OFF circle goes to the beginning and start decreasing from there.

**Comment by algazarra** [comment]
Yes, I did notice that detail, but faster update intervals won't let you see it. Just my opinion . let's wait for more feedback. Anyway, this is bells and whistles.

**Comment by dllud** [comment]
>  faster update intervals won't let you see it

Why? You'll only miss it if ALL your alarms are with the ON/OFF circle painted in full. And if they are like that, why on earth are you clicking refresh? Your values are up-to-date. It makes sense to have no feedback in such corner case, because by hitting refresh you're doing nothing.

Anyway, users with using a short update interval won't feel the need to click refresh.

With update intervals where refreshing makes sense (e.g. the 5 min I use) you can clearly see the circles filling. And by the way, I only click refresh if the circles are half-way through or similar. Otherwise I don't refresh because I know I am seeing a fresh value.

**Comment by algazarra** [comment]
Yes, that's true.
