### ISSUE TITLE
Option to disable the "no Internet" alarm

### ISSUE THREAD

**Issue by simon-v** [drpout/boilr#238]
For mobile phones, the lack of an Internet connection is a common occurrence. The alarm on the disappearance of an internet connection provides no new information to people for whom this is the norm. As such, it may be sensible to allow turning off this distraction.

**Comment by dllud** [comment]
Thanks for the report @simon-v 

This issue has been solved and committed to master more than a year ago in #79. Unfortunately we haven't made a release since then yet. A new release is planned for soon (a couple of weeks), you'll see the changes by then. Meanwhile you can compile the apk yourself, or use the one inside the following zip that I've compiled myself: [boilr-0.7.0.zip](https://github.com/drpout/boilr/files/585777/boilr-0.7.0.zip).
