### ISSUE TITLE
Bitmex

### ISSUE THREAD

**Issue by heaven2** [drpout/boilr#260]
Bitmex XBT has 2. Swap and quarterly. For some reason when selecting XBT on Bitmex it will randomly change between swap and quarterly. 

Is there a reliable way to pick swap and not have the quarterly price randomly appear?

It happens when just playing about trying to set alarms and touching stuff. 

Thanks!

**Comment by dllud** [comment]
Problem due to multiple pairs with the same coin and exchange: XBT/USD.
Fixed it by renaming the second pair as XBT/U17 (same nomenclature used by BitMEX).
Fix is now available on master branch. You can compile it yourself or install the following apk that I have just built (signed with our release key): [boilr-0.8.0.apk.zip](https://github.com/drpout/boilr/files/1171452/boilr-0.8.0.apk.zip)
