### ISSUE TITLE
Bitcoin.de

### ISSUE THREAD

**Issue by beatnickgr** [drpout/boilr#271]
For bitcoin.de the widget is retrieving the price of the [last transaction](https://www.bitcoin.de/en/btceur/trade/neueste-transaktionen), as a result, if one person buys by mistake at 4000 when the price is 3000, the alarm will ring. If it's an alarm on a price hit it will ring once, if it's a price change it will ring again when somebody buys at the current price.

Looking at the [48h chart](https://www.bitcoin.de/en/chart) i see transactions a lot of transactions at wrong prices especially between 2 and 5 AM (when people are tired), when the average price has not really changed. All these false alarms makes the Boilr completely unusable.

Expected behaviour would be the alarm will only ring when the **average** price has changed.

Instead of the last transaction price, we could retrieve the "Current Bitcoin price" which is an average of the last transactions of the last 15'.

**Comment by dllud** [comment]
Boilr is targeted to traders, thus all alarms fetch the last price, because traders need to know what is happening **live** on the exchanges. Using a 15 minute average would give traders an outdated view of the market. That's something they are looking for in charts, not in a price app. Thus we cannot use an average price for Bitcoin.de (or any other exchange).

The issue your are facing stems from the fact that Bitcoin.de isn't a regular exchange, but rather a "marketplace" as they call themselves.
On a regular exchange all money is deposited with the exchange, which enables it to fulfil market orders based solely on the price and age of orderbook entries.
On Bitcoin.de money is transfered directly from buyers' to seller's bank accounts, which forced Bitcoin.de to add many more restrictions besides price and age: availability of express trade, trust level, legitimization status and seat of bank.
The price spikes that you see are not due to people being tired, but rather from not fulfilling the requirements for the cheapest orderbook entries (which tend to require express trade and a high legitimization status).

Tip: if you want to follow Bitcoin price in EUR create an alarm for Kraken. That will give you a preview of what will happen on Bitcoin.de. Bitcoin.de is such a small market that is just follows the price on the big exchanges.

**Comment by beatnickgr** [comment]
If you tell traders to use kraken, not bitcoin.de, then what's the use of offering an alarm for bitcoin.de in the first place?

When the price is 3150€, if I want to purchase at 3000€, and by mistake I place a sell order at 3000€, then somebody will accept the order immediately, which will create a spike.
Then, if you have set an alarm at 3000€, Boiler will ring although you cannot buy at this price anymore (it was a 1 time offer because of my mistake).
Try it yourself for 24h to check how many false alarm you'll have.

Bitcoin.de is indeed a market place, because i buy and sell to other users of the platform, and not to the platform itself. This is because of this particularity that it needs a different programming.

May i suggest that you offer both options, (1) bitcoin.de last price (2) bitcoin.de average price.
