### ISSUE TITLE
Adding support for shifting sites

### ISSUE THREAD

**Issue by eloyesp** [drpout/boilr#290]
There are a couple of sites like https://changelly.com/ , https://shapeshift.io/ or https://godex.io/ that allows exchange without creating an account, but it seems that none of those sites are supported, would it be possible to add support for those?

Seems that the site https://www.shiftex.io provides information for most of them.

**Comment by dllud** [comment]
We do not have sites like that as a policy. Those sites are a "Bureau de Change", and not a real exchange with an orderbook. They are not market makers, they buy and sell on real exchanges and then resell on their platform with an added fee.
Boilr is targeted for traders, for whom knowing price on a site like that is pointless. But even for non-traders, it makes sense to follow the price on a real exchange, because that's the price you will see on all "Bureau de Change"s a few seconds later (with an added fee).
